# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.ssh.insert_key = false
    config.vm.define "LOAD01"
    config.vm.hostname = "LOAD01"
    config.vm.network 'public_network', ip: '192.168.1.31', netmask: '255.255.255.0'
    config.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)
  
    config.vm.provider :vmware_esxi do |esxi|
      esxi.esxi_hostname = '192.168.1.2'
      esxi.esxi_username = 'root'
      esxi.esxi_password = 'Jm2003jm/'
      esxi.esxi_virtual_network = ['VM Network']
      esxi.guest_memsize = '2048'
      esxi.guest_numvcpus = '1'
    end
  
    # Provisioning configuration for Ansible.
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        ansible_user: 'vagrant',
        ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
      }
    end
  end
