---
- hosts: all
  become: yes

  tasks:
  - name: Ensure chrony (for time synchronization) is installed.
    apt:
      name: chrony
      state: present

  - name: Ensure chrony is running.
    service:
      name: chronyd
      state: started
      enabled: yes

  - name: Install mariadb
    apt: 
      name: mariadb-server
      state: present
      update_cache: true

  - name: Install pip
    apt:
      name: python3-pip
      state: present

  - name: Install PyMySQL
    pip:
      name: pymysql
      state: present

  - name: Allow port 3306
    ufw:
      rule: allow
      port: "3306"
      proto: tcp
  
  - name: Pas MariaDB configuratie aan
    become: true
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address\s+=\s+127\.0\.0\.1$'
      line: 'bind-address = 0.0.0.0'
      state: present
      backup: yes
    notify: Restart MariaDB

  - name: Maak MySQL gebruiker aan voor webserver
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_host: localhost
      login_user: root
      login_password: null
      name: 'webserver'
      password: 'wachtwoord'
      priv: '*.*:ALL'
      host: '%'
      append_privs: yes
      state: present
    become: true

  - name: Maak database aan
    mysql_db:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_host: localhost
      login_user: root
      login_password: null
      name: "voorbeelddatabase"
    become: true

  - name: Maak tabel aan
    mysql_query:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_host: localhost
      login_user: root
      login_password: null
      login_db: voorbeelddatabase
      query: >
        CREATE TABLE tabel1 (
          id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
          naam VARCHAR(255) NOT NULL,
          leeftijd INT(11) NOT NULL
        )
    become: true

  - name: Voeg voorbeeldrecords toe aan tabel1
    mysql_query:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_host: localhost
      login_user: root
      login_password: null
      login_db: voorbeelddatabase
      query:
        - INSERT INTO tabel1 (id, naam, leeftijd) VALUES (1, "John Doe", 30), (2, "Jane Doe", 25);
    become: true

  handlers:
    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted